# Generated by Django 2.2.7 on 2019-11-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionaire',
        ),
    ]
